### ISSUE TITLE
Chat log not showing chat

### ISSUE THREAD

**Issue by rustinpieces** [WaferMouse/L3-37#2]
Chat shows names but no messages, only [S]  
L3-37 v105

![Clipboard01](https://user-images.githubusercontent.com/29709133/87848196-c9461e80-c8ab-11ea-9e58-0fd62d8a923a.jpg)
![Clipboard02](https://user-images.githubusercontent.com/29709133/87848197-c9461e80-c8ab-11ea-8268-77e24d2aee4c.jpg)

**Comment by WaferMouse** [comment]
Oops! This slipped the net when updating for the library changes in Python 3, thanks for reporting it! The chat viewer is long overdue an overhaul in the next release, in the meantime as a temporary fix you can download the following file and place it in the edmc-L3-37 directory: https://raw.githubusercontent.com/WaferMouse/L3-37/master/chat_viewer.py

Closing as fixed in commit https://github.com/WaferMouse/L3-37/commit/da592a75e1f6f04cc70fd1579374792f024067b2
